In [1]:
import torch

# 1로 채워진 2*3 matrix
a = torch.ones((2, 3))
# default float32
print(a.dtype)

# int16 타입으로 1로 채워진 2*3 matrix 생성
b = torch.ones((2, 3), dtype=torch.int16)
print(b)

# 랜덤 변수에 20씩 곱한값을 2*3 matrix를 float64로 생성
c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

# int32타입으로 변경한 matrix b를d에 복사
d = b.to(torch.int32)
print(d)

# double타입 1로 채워진 10*2 matrix 생성
double_d = torch.ones(10, 2, dtype=torch.double)
# short타입으로 생성된 1*2 matrix 생성
short_e = torch.tensor([[1, 2]], dtype=torch.short)

# double타입 0으로 채워진 10*2 matrix 생성
double_d = torch.zeros(10, 2).double()
# short타입 1로 채워진 10*2 matrix 생성
short_e = torch.ones(10, 2).short()

# 0으로 채워진 10*2 matrix를 double 타입으로 변환
double_d = torch.zeros(10, 2).to(torch.double)
# 1로 채워진 10*2 matrix를 short 타입으로 변환
short_e = torch.ones(10, 2).to(dtype=torch.short)

# 0으로 채워진 10*2 matrix를 double 타입으로 변환
double_d = torch.zeros(10, 2).type(torch.double)
# 1로 채워진 10*2 matrix를 short 타입으로 변환
short_e = torch.ones(10, 2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
# 더 큰 자료형 따라감
print((double_f * short_g).dtype)


torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 5.9940,  1.5436, 11.1582],
        [ 3.3226, 11.7254, 12.3198]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.float64
torch.int16
torch.float64
