In [1]:
import torch

# vector * constant의 곱
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

print("#" * 50, 1)

# 브로드캐스팅을 통해 텐서간의 차
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)

print("#" * 50, 2)

# 텐서 + constant
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)
print(t5 - 2.0)
print(t5 * 2.0)
print(t5 / 2.0)

print("#" * 50, 3)


# 이미지 픽셀값 0~1로 nomalize
def normalize(x):
  return x / 255


# 28*28 이미지 nomalize
t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

print("#" * 50, 4)

# 브로드캐스팅 합
t7 = torch.tensor([[1, 2], [0, 3]])  # 2*2
t8 = torch.tensor([[3, 1]])  # 1*2
t9 = torch.tensor([[5], [2]])  # 2*1
t10 = torch.tensor([7])  # 1
print(t7 + t8)
print(t7 + t9)
print(t8 + t9)
print(t7 + t10)

print("#" * 50, 5)

# 브로드캐스팅을 통한 곱
# t12의 첫번째 차원이 4로 브로드캐스팅 됨
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)
print(t12.shape)

# 브로드캐스팅
# t14 첫번째 차원 -> 4
# t14 세번째 차원 -> 2
t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)
print(t14.shape)

# t16 첫번째 차원 -> 4
# t16 두번쨰 차원 -> 3
t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)
print(t16.shape)


# t18 첫번째 차원 -> 5
# t18 두번째 차원 -> 4
t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)
print((t17 + t18).size())

print("#" * 50, 6)

# t20 첫번째 차원 -> 5
# t20 세번째 차원 -> 4
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

# t21의 브로드캐스팅
t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())

# t24의 브로드캐스팅
t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

print("#" * 50, 7)

t27 = torch.ones(4) * 5
print(t27)

# 2승으로 각 원소 제곱
t28 = torch.pow(t27, 2)
print(t28)

exp = torch.arange(1., 5.)
a = torch.arange(1., 5.)
t29 = torch.pow(a, exp)
print(t29)


tensor([2., 4., 6.])
################################################## 1
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2
tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3
torch.Size([3, 28, 28])
################################################## 4
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1