In [1]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
# 3*2로 변경
t2 = t1.view(3, 2)
# 1*6으로 변경
t3 = t1.reshape(1, 6)
print(t2)
print(t3)

# arange로 1*8 matrix 생성후 2*4로 변경
t4 = torch.arange(8).view(2, 4)
# arange로 1*6 matrix 생성후 2*3으로 변경
t5 = torch.arange(6).view(2, 3)
print(t4)
print(t5)

print("#" * 50, 1)

# 1*3*1  matrix
t6 = torch.tensor([[[1], [2], [3]]])
# 크기가 1인 차원 지우기
t7 = t6.squeeze()

# 첫번쨰 차원이 1인경우 차원 지우기
t8 = t6.squeeze(0)
print(t7)
print(t8)

print("#" * 50, 2)

t9 = torch.tensor([1, 2, 3])

# 1인 차원 추가
t10 = t9.unsqueeze(1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)
print(t12, t12.shape)

print("#" * 50, 3)


t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# 1행으로 피기
t14 = t13.flatten()

print(t14)


t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

# 두번째 차원부터 피기
t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

print("#" * 50, 4)

t18 = torch.randn(2, 3, 5)
print(t18.shape)

# 순서 재배치
print(torch.permute(t18, (2, 0, 1)).size())

t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])


t20 = torch.permute(t19, dims=(0, 1))
t21 = torch.permute(t19, dims=(1, 0))
print(t20)
print(t21)


# transpose
t22 = torch.transpose(t19, 0, 1)

print(t22)

# transpose
t23 = torch.t(t19)

print(t23)


tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1
tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4
torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
