In [2]:
import torch
import numpy as np

# array 생성 후 torch.Tensor type으로 t1에 복사
l1= [1,2,3]
t1=torch.Tensor(l1)

# array 생성 후 torch.tensor type으로 t2에 복사
l2=[1,2,3]
t2=torch.tensor(l2)

# array 생성 후 torch.as_tensor type으로 t3에 복사
l3=[1,2,3]
t3=torch.as_tensor(l3)

l1[0]=100
l2[0]=100
l3[0]=100

print(t1)
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [3]:
# numpy array 생성 후 torch.Tensor으로 t4에 복사
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

# numpy array 생성 후 torch.tensor으로 t5에 복사
l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

# numpy array 생성 후 torch.as_tensor으로 l6에 복사
# 파이썬 list와 ndarray의 구조적 차이로 오는 현상 재현
# l6을 변경시 tensor로 타입변환하는 과정에 있어
# t6는 l6을 참고하여 값을 표현
l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)


tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])
