In [2]:
import torch

# 10~ 20중 랜덤으로 1,2 matrix 값을 채워 생성
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

# 랜덤한 수로 1,3 matrix 생성
t2 = torch.rand(size=(1, 3))
print(t2)

# 평균이 0이고 분산이 1인 정규 분포를 따르는 랜덤한 수로 1,3 matrix 생성
t3 = torch.randn(size=(1, 3))
print(t3)

# 평균이 10.0이고 분산이 1.0인 정규 분포를 따르는 랜덤한 수로 (3,2) matrix 생성
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

# 0.0에서 5.0까지 3번에 걸친 수(동일한 간격)로 matrix 생성
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

# 시작 default 0, 마지막 5, step default 1
t6 = torch.arange(5)
print(t6)

# 난수 생성 시드 고정
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)


tensor([[17, 12]])
tensor([[0.0453, 0.5035, 0.9978]])
tensor([[0.7419, 0.5923, 0.2908]])
tensor([[ 9.2270, 10.0961],
        [ 9.4067,  9.5878],
        [10.0763, 11.1161]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
