In [1]:
import torch

x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

# 1행 출력
print(x[1])
# 1열 출력
print(x[:, 1])
# 1행 2열 출력
print(x[1, 2])
# 마지막 열 출력
print(x[:, -1])

print("#" * 50, 1)

# 1행부터 마지막 행까지 출력
print(x[1:])
# 1행부터 마지막, 3열부터 마지막 까지의 원소 출력
print(x[1:, 3:])

print("#" * 50, 2)

# 1행 ~ 4행, 2열의 원소 1
y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

print("#" * 50, 3)

z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
# 처음부터 2행까지 출력
print(z[:2])
# 1행부터 마지막, 1열부터 3열까지의 원소 출력
print(z[1:, 1:3])
# 모든 행, 1열부터 마지막 열까지의 원소 출력
print(z[:, 1:])

# 1행부터 마지막, 1열부터 3열까지의 원소 0
z[1:, 1:3] = 0
print(z)


tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])
