In [2]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

# 0번쨰 차원에서 stack
t3 = torch.stack([t1, t2], dim=0)
# 0번째 차원에서 unsqueeze하고 cat
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
# t4와 t3 같은지 비교
print(t3.shape, t3.equal(t4))

# 1번쨰 차원에서 stack
t5 = torch.stack([t1, t2], dim=1)
# 1번째 차원에서 unsqueeze하고 cat
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
# t6와 t5 같은지 비교
print(t5.shape, t5.equal(t6))

# 2번쨰 차원에서 stack
t7 = torch.stack([t1, t2], dim=2)
# 2번째 차원에서 unsqueeze하고 cat
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
# t8와 t7 같은지 비교
print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

t9 = torch.arange(0, 3)
t10 = torch.arange(3, 6)

print(t9.size(), t10.size())

# 0번쨰 차원에서 stack
t11 = torch.stack((t9, t10), dim=0)
print(t11.size())
print(t11)

# 0차원에서 unsqueeze하고 cat
t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
# t8와 t7 같은지 비교
print(t11.equal(t12))  # 출력: True

# 1차원에서 stack
t13 = torch.stack((t9, t10), dim=1)
print(t13.size())
print(t13)

# 1차원에서 unzqueeze하고 cat
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
# t14와 t13 같은지 비교
print(t13.equal(t14))


torch.Size([2, 6, 3])
################################################## 1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
t