In [1]:
import torch

t1 = torch.ones(size=(5,))
t1_like = torch.ones_like(input=t1) # t1과 같은 shape과 데이터 타입을 가지고 모든 값이 1인 텐서를 생성
print(t1)
print(t1_like)

t2 = torch.zeros(size=(6,))
t2_like = torch.zeros_like(input=t2) # t2와 같은 shape과 데이터 타입을 가지고 모든 값이 0인 텐서를 생성
print(t2)
print(t2_like)

t3 = torch.empty(size=(4,))
t3_like = torch.empty_like(input=t3) # t3와 같은 shape과 데이터 타입을 가지고 초기화 되지 않은 값을 가지는 텐서 생성
print(t3)
print(t3_like)

t4 = torch.eye(n=3) # indentity matrix생성
print(t4)


tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([1.5414e-44, 0.0000e+00, 1.5414e-44, 1.9618e-44])
tensor([0., 0., 0., 0.])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
